# This file was generated by GoReleaser. DO NOT EDIT.
cask "dash0" do
  version "1.16.5"

  on_macos do
    on_intel do
      sha256 "3a55505f6b432d71d80baeff956b9817165d1d6618ebae44e1f53f21367b501b"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "47a92c895c56485f36e1e4a620d21e560b1e9cb762a8fa7ff7bc8a720e4c0d63"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "164ba82f24139d305d32896acab13e423d58d2c4a1bd9dfd758f9a8dbfee95e1"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "110582911e18cd71c6ac45d2da969e200ea6913eee4eeaa4c595894429ff520d"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dash0"
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dash0"
  bash_completion "completions/dash0.bash"
  fish_completion "completions/dash0.fish"
  zsh_completion "completions/dash0.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
