# This file was generated by GoReleaser. DO NOT EDIT.
cask "dash0" do
  version "1.16.2"

  on_macos do
    on_intel do
      sha256 "6daa50c67e3ad0fc12a4ef53fbaac817c1e792c6576ddead290d6e397b732047"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a0ee28db9a0604ec8064d95aa82827553dba510dffb330af6749210dcc2c9ff"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31542551ca333ba17cd988175cc62bf14c605cec64e77b671de6853356a27fb8"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "580ad7b15fe2239ba0280c7f6099480b7565e3eaad7e07789927478c8d09937f"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dash0"
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dash0"
  bash_completion "completions/dash0.bash"
  fish_completion "completions/dash0.fish"
  zsh_completion "completions/dash0.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
