# This file was generated by GoReleaser. DO NOT EDIT.
cask "dash0" do
  version "1.15.2"

  on_macos do
    on_intel do
      sha256 "d0e1560a3b920064f687ef24c3d0b74cb59e45611d228f7513e8ec85c23f8731"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb5e7798205bf421d513bf8b78d1a172f2e18ce363fa1e7fb0ad9c54b6230d9a"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bd20a6ce9b4a3d7749bd373ae968bae7486af469e8a723b5931d8a33cee285a2"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "71367675d4650b73f9559493a23b5609b610be1190df4b2d9087ef0b7d3b0c2d"
      url "https://github.com/dash0hq/dash0-cli/releases/download/v#{version}/dash0_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dash0"
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dash0"
  bash_completion "completions/dash0.bash"
  fish_completion "completions/dash0.fish"
  zsh_completion "completions/dash0.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
